Made a FruitShop report writer which takes info from one .csv file an…
mate-academy/jv-fruit-shop pull request #1001
Opened 2023-11-24 11:28 UTC by maxymmusiienko

…d writing to another .csv file. Created Dao interface implementation for working with file, used pattern strategy for following SOLID principles.

2023-11-24 17:21 UTC, okuzan requested changes
Good job! Read the comments to find out how to improve your code 👇

2023-11-24 17:21 UTC, okuzan commented on src/main/java/main/FruitStoreMain.java
> +        FruitTransactionStorage fruitTransactionStorage = commandDao.read();
This should just be List<FruitTransaction> . It's not a storage, naming is confusing. You don't need to store, Just parse input in to list, and then pass it to next service

2023-11-24 17:21 UTC, okuzan commented on src/main/java/service/FruitStoreService.java
> +        strategyMap.put(FruitTransaction.Operation.BALANCE, new BalanceStrategy());
use Map.of, pass as arguemnt instead

2023-11-24 17:21 UTC, okuzan commented on src/main/java/service/FruitStoreService.java
> +
```suggestion
```

2023-11-24 17:21 UTC, okuzan commented on src/main/java/service/FruitStoreService.java
> +            if (strategy != null) {
better throw exception if strategy not found

2023-11-24 17:21 UTC, okuzan commented on storage.csv
> +    type,fruit,quantity
src/main/resources

2023-11-24 17:21 UTC, okuzan commented on src/main/java/strategy/PurchaseStrategy.java
> +    public void apply(FruitStorage fruitStorage, FruitTransaction transaction) {
what if we don't have enough to sell

2023-11-24 17:21 UTC, okuzan commented on src/main/java/core/basesyntax/db/CommandDaoImpl.java
> +                        .setOperation(FruitTransaction
separate your concerns. Create FileReader which only reads, and another service to parse the data into models. Think about validation - what if will get NumberFormatException from .parseInt or enum code won't be found?

2023-11-24 20:55 UTC, maxymmusiienko commented
> Good job! Read the comments to find out how to improve your code 👇

thank you! Frankly speaking it was a difficult task for me. I will fix all the mistakes

2023-11-25 10:29 UTC, olekskov requested changes

2023-11-25 10:29 UTC, olekskov commented on src/main/java/service/ValidationDataException.java
> +package service;
why exception is in service package?

2023-11-25 10:29 UTC, olekskov commented on src/main/java/service/StrategyException.java
> +package service;
same

2023-11-25 10:29 UTC, olekskov commented on src/main/java/service/InsufficientInventoryException.java
> +package service;
same

2023-11-25 10:29 UTC, olekskov commented on src/main/java/service/FruitStoreService.java
> +public class FruitStoreService {
why reader and writer implement interface but this service does not?

2023-11-25 10:29 UTC, olekskov commented on src/main/java/service/FruitStoreService.java
> +        FruitStorage fruitStorage = new FruitStorage();
In order to have flexible solution you should obtain things you rely on in constructor. So your service can be created to work with any map and any storage that may be created in future:
```suggestion
    public FruitStoreService(Map<FruitTransaction.Operation, TransactionStrategy> strategyMap, FruitStorage fruitStorage ) {
        this.strategyMap = strategyMap;
        this.fruitStorage = fruitStorage;
    }

    public FruitStorage processTransactions(List<FruitTransaction> transactions) {
```
map and fruitStorage should be initialized in main class and passed as arguments

2023-11-26 10:19 UTC, Sanderfuck requested changes

2023-11-26 10:19 UTC, Sanderfuck commented on src/main/java/db/FruitStorage.java
> +        return fruitInventory.entrySet();
Why do you use this type?

2023-11-26 10:19 UTC, Sanderfuck commented on src/main/java/service/FileReaderImpl.java
> +    }
Single responsibility!!! Method read must only read! Divide this logic

2023-11-26 10:19 UTC, Sanderfuck commented on src/main/java/service/FileWriterImpl.java
> +                        + System.lineSeparator());
Better use stringBuilder

2023-11-27 12:51 UTC, okuzan requested changes

2023-11-27 12:51 UTC, okuzan commented on src/main/java/service/FileReaderImpl.java
> +    private FruitTransaction extractTransaction(String line) {
The logic is fine, but you should place it in a separate service. The reader should return raw content, like List of String, not a list of DTOs. Then you pass it to FruitTransactionParser (you may name it differently) and it returns a list of transactions. That's what we meant by the separation of concerns

2023-11-27 12:51 UTC, okuzan commented on src/main/java/db/FruitStorage.java
> +        return fruitInventory.entrySet();
for report generation

2023-11-27 13:48 UTC, okuzan approved these changes
Good job! Congratulations 🥳

2026-05-28 12:17 UTC, closed without merging