Implemented jv-fruit-shop
mate-academy/jv-fruit-shop pull request #1120
Opened 2024-04-09 18:39 UTC by ynik404

2024-04-10 10:24 UTC, Rommelua commented on src/main/java/core/basesyntax/db/Storage.java
> +    public static final List<FruitTransaction> fruitTransactions = new ArrayList<>();
On the Storage fruits are kept, not Transactions
```suggestion
    public static final Map<String, Integer> fruits = new HashMap<>();
```

2024-04-12 10:42 UTC, Rommelua requested changes

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/Main.java
> +        String report = reportCreator.create(new StorageDaoImpl().getAll());
```suggestion
        String report = reportCreator.create();
```

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/Main.java
> +        Executor executor = new ExecutorImpl(new StorageDaoImpl(), operationStrategy);
```suggestion
        StorageDao storageDao = new StorageDaoImpl();
        Executor executor = new ExecutorImpl(storageDao, operationStrategy);
```

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/Main.java
> +        ReportCreator reportCreator = new ReportCreatorImpl();
```suggestion
        ReportCreator reportCreator = new ReportCreatorImpl(storageDao);
```

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/db/Storage.java
> +    public static final List<FruitTransaction> fruits = new ArrayList<>();
**fruits** and **Transaction** are different things. Fruits are kept in the Storage in Fruit Shop.
```suggestion
    public static final Map<String, Integer> fruits = new HashMap<>();
```

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/service/ReportCreator.java
> +    String create(List<FruitTransaction> fruitTransactions);
```suggestion
    String createReport();
```

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/service/impl/ParserImpl.java
> +                        || line.startsWith("r"))
remove this hardcode.
We should just skip the first line

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/service/impl/ParserImpl.java
> +        if (fields.length < 3) {
magic number

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/service/impl/ParserImpl.java
> +            operation = operation.getOperationFromLetter(fields[0]);
```suggestion
            FruitTransaction.Operation operation = FruitTransaction.Operation.getByCode(fields[CODE_INDEX]);
```

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/model/FruitTransaction.java
> +        public Operation getOperationFromLetter(String letter) {
Why 'letter'??
```suggestion
        public static Operation getByCode(String code) {
```

2024-04-12 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/service/impl/ReaderImpl.java
> +        return data;
```suggestion
        try {
            return Files.readAllLines(Path.of(filePath));
        } catch (IOException e) {
            throw new RuntimeException("Can't find file by path: " + filePath, e);
        }
```

2024-04-12 14:31 UTC, kerrrusha approved these changes

2024-04-12 14:31 UTC, kerrrusha commented on src/main/java/core/basesyntax/service/impl/ParserImpl.java
> +        if (fields.length < 3) {
not fixed

2024-04-12 14:31 UTC, kerrrusha commented on src/main/java/core/basesyntax/service/impl/ReportCreatorImpl.java
> +                    if (fruit.getValue() < 0) {
magic number

2025-02-18 16:43 UTC, closed without merging