project is ready for the code review, final commit
mate-academy/jv-fruit-shop pull request #1121
Opened 2024-04-10 06:17 UTC by misterSokor

2024-04-10 11:23 UTC, Rommelua requested changes

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/Main.java
> +        String outputFilePath = "src/main/resources/output.csv";
Make them constants

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/Main.java
> +                parseService.parseFromString(transactions);
```suggestion
        List<String> fileContent = readerService.readFile(inputFilePath);

        List<FruitTransaction> transactions =
                parseService.parseFromString(fileContent);
```

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/Main.java
> +        writerSerivce.writeToFile(outputFilePath, fruitCounts);
```suggestion
        processorService.processTransaction(transactions);
        List<String> report = reportService.createReport();
        writerSerivce.writeToFile(outputFilePath, report);
```

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/db/Storage.java
> +            Collections.synchronizedList(new ArrayList<>());
There are Fruits in the Storage, not FruitTransactions
```suggestion
    public static final Map<String, Integer> fruits = new HashMap<>();
```

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/model/FruitTransaction.java
> +        private final String firstLetterOfOperationType;
```suggestion
        private final String code;
```

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/model/FruitTransaction.java
> +        public static Operation getNameOfType(String letterType) {
```suggestion
        public static Operation getByCode(String code) {
```

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/service/impl/ParseServiceImpl.java
> +            parsedData.add(new FruitTransaction(operationType, fruit, quantity));
add constants for numbers

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/service/impl/ReaderServiceImpl.java
> +        }
```suggestion
        try {
            return Files.lines(Path.of(inputFile))
        } catch (IOException e) {
            throw new RuntimeException("Can't read from the file: " + inputFile, e);
        }
```

2024-04-10 11:23 UTC, Rommelua commented on src/main/java/service/impl/TransactionProcessorServiceImpl.java
> +    private Map<String, Integer> fruitCounts;
Use Storage
```suggestion
```

2024-04-12 09:46 UTC, MentorMA requested changes

2024-04-12 09:46 UTC, MentorMA commented on src/main/java/Main.java
> +        return operationStrategies;
Better use map.of

2024-04-12 09:46 UTC, MentorMA commented on src/main/java/service/impl/ReportServiceImpl.java
> +        report.add("fruit,quantity");
Save it to constant

2024-04-12 09:46 UTC, MentorMA commented on src/main/java/service/impl/ReportServiceImpl.java
> +        List<String> report = new java.util.ArrayList<>();
resolve import of ArrayList

2024-04-13 12:14 UTC, MentorMA approved these changes

2025-08-13 04:20 UTC, closed without merging