functionality is implemented
mate-academy/jv-fruit-shop pull request #1127
Opened 2024-04-19 15:37 UTC by vladshender

2024-04-20 15:29 UTC, olekskov requested changes
Good job overall but some enhancements required

2024-04-20 15:29 UTC, olekskov commented on src/main/java/core/basesyntax/service/operation/PurchaseOperationHandler.java
> +        return before - after;
need to add handling preventing to have negative balance in storage

2024-04-20 15:29 UTC, olekskov commented on src/main/java/core/basesyntax/service/storage/StorageServiceImpl.java
> +            );
```suggestion
            operationHandler.process(transaction);
```

2024-04-20 15:29 UTC, olekskov commented on src/main/java/core/basesyntax/service/storage/StorageServiceImpl.java
> +        for (FruitTransaction fruit : fruits) {
```suggestion
    public void transfer(List<FruitTransaction> transactions) {
        for (FruitTransaction transaction : transactions) {
```

2024-04-20 15:29 UTC, olekskov commented on src/main/java/core/basesyntax/service/operation/OperationHandler.java
> +    Integer calculateQuantity(Integer before, Integer after);
let handler take transaction and change storage state accordingly
```suggestion
    void process(Transaction transaction);
```

2024-04-22 08:55 UTC, Vasul-Pankiv requested changes

2024-04-22 08:55 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/db/FruitStorageImpl.java
> +    private Map<String, Integer> fruitStorage = new HashMap<>();
make this map static, to be sure you always work with the same storage

2024-04-23 10:56 UTC, Rommelua requested changes

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/dao/reader/ReaderCsvImpl.java
> +        return transactions;
```suggestion
        try {
            return  Files.readAllLines(fileName);
        } catch (IOException e) {
            throw new RuntimeException("Can`t read data from file: " + fileName, e);
        }
```

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/dao/writer/WriterCsv.java
> +    void writeToFile(Path filePath, List<String> storageInfo);
```suggestion
    void writeToFile(Path filePath, List<String> lines);
```

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/dao/writer/WriterCsvImpl.java
> +    public void writeToFile(Path filePath, List<String> storageInfo) {
```suggestion
    public void writeToFile(Path filePath, List<String> lines) {
```

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/dao/writer/WriterCsvImpl.java
> +                    + e.getMessage());
![image](https://github.com/mate-academy/jv-fruit-shop/assets/20326858/9ee08fb2-b482-4009-9743-463fa0761e4f)

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/service/report/ReportService.java
> +    List<String> report(Map<String, Integer> fruitStorage);
Pass fruitStorage to impl constructor
```suggestion
    List<String> createReport();
```

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/service/storage/StorageService.java
> +    void transfer(List<FruitTransaction> fruits, FruitStorage storage);
```suggestion
    void transfer(List<FruitTransaction> fruits);
```

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/service/operation/OperationHandler.java
> +    void process(FruitTransaction transaction, FruitStorage storage);
Pass fruitStorage to impl constructor
```suggestion
    void process(FruitTransaction transaction);
```

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/service/FruitService.java
> +}
delete this interface

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/service/FruitServiceImpl.java
> +public class FruitServiceImpl implements FruitService {
```suggestion
public class Main {
```

2024-04-23 10:56 UTC, Rommelua commented on src/main/java/core/basesyntax/service/FruitServiceImpl.java
> +    public void countToCsv(Path fromFile, Path toFile) {
```suggestion
    public static void main(String... args) {
```
![image](https://github.com/mate-academy/jv-fruit-shop/assets/20326858/fc74e5b0-c360-433f-983f-ba2404d0b032)

2024-04-25 13:03 UTC, kerrrusha requested changes
cant see `main` method

2024-04-25 13:03 UTC, kerrrusha commented on src/main/java/core/basesyntax/service/parser/ParserCsvImpl.java
> +    }
move this method to the Operation enum

2024-04-25 13:03 UTC, kerrrusha commented on src/main/java/core/basesyntax/service/parser/ParserCsvImpl.java
> +    private static final String DELLIMETER = ",";
```suggestion
    private static final String DELIMITER = ",";
```

2024-04-25 20:15 UTC, sarakhmen approved these changes
LGTM!

2026-03-08 07:29 UTC, closed without merging