Fruit shop generator report
mate-academy/jv-fruit-shop pull request #168
Opened 2021-07-05 17:31 UTC by Daniel1004K

2021-07-05 19:51 UTC, Veronika-Alekseienko requested changes
Well done !!)

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/service/FileCsvWriter.java
> +            throw new RuntimeException("There is a problem with saving", e);
```suggestion
            throw new RuntimeException("There is a problem with saving" + filePath, e);
```

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/service/FileCsvWriter.java
> +    public boolean write(String report, String path) {
```suggestion
    public boolean write(String report, String filePath) {
```

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/service/Parser.java
> +    FruitDto parse(String element);
```suggestion
    FruitDto parse(String line);
```

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/service/ParserCsv.java
> +        String[] partsOfElement = element.split(",");
make constant for ","

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/service/Reader.java
> +    List<String> read(String fileName);
```suggestion
    List<String> readFromFile(String fileName);
```

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/service/Writer.java
> +    boolean write(String report, String path);
```suggestion
    boolean write(String report, String filePath);
```

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/srategy/PurchaseHandler.java
> +        return count - fruitDto.getCount();
let's make variable for    count - fruitDto.getCount()

2021-07-05 19:51 UTC, Veronika-Alekseienko commented on src/main/java/core/basesyntax/srategy/SupplyHandler.java
> +        return count + fruitDto.getCount();
let's make variable for   count + fruitDto.getCount()

2021-07-06 05:51 UTC, Veronika-Alekseienko approved these changes

2021-07-06 06:46 UTC, KseniiaMakarova requested changes

2021-07-06 06:46 UTC, KseniiaMakarova commented on .gitignore
> +/src/main/resources/
let's remove this line) we already pushed these files to PR, and it is ok

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/Main.java
> +    private static final String STORAGE_PATH = "src/main/resources/storage.csv";
```suggestion
    private static final String PATH_INPUT_FILE = "src/main/resources/storage.csv";
```

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dto/FruitDto.java
> +    private int count;
```suggestion
    private int quantity;
```

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/FileCsvReader.java
> +public class FileCsvReader implements Reader {
```suggestion
public class CsvFileReader implements FileReader {
```

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/FileCsvReader.java
> +            throw new RuntimeException("Problem with file",e);
let's pass fileName to the exception

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/FileCsvWriter.java
> +public class FileCsvWriter implements Writer {
```suggestion
public class FileWriterImpl implements FileWriter {
```
we can actually write any content to any file, not only csv

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/FileCsvWriter.java
> +            Files.write(Path.of(filePath),report.getBytes(StandardCharsets.UTF_8));
does Files.write already create a file if needed?

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/FruitReport.java
> +public class FruitReport {
```suggestion
public class FruitReportService implements ReportService {
```

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/FruitReport.java
> +    private final Map<Fruit, Integer> storage;
I think we can better use this as local variable

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/ParserCsv.java
> +public class ParserCsv implements Parser {
```suggestion
public class ParserImpl implements Parser {
```

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/ValidatorCsv.java
> +    public boolean test(String o) {
what is `o`?

2021-07-06 06:46 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/srategy/SupplyHandler.java
> +    }
optional: we can use 1 handler both for supply and return

2021-07-06 09:18 UTC, KseniiaMakarova requested changes

2021-07-06 09:18 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/CsvFileWriter.java
> +public class CsvFileWriter implements FileWriter {
>we can actually write any content to any file, not only csv

what about this comment?

2021-07-06 09:18 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/service/FruitReportService.java
>      }
do we need the empty constructor?

2021-07-06 10:52 UTC, KseniiaMakarova approved these changes

2023-04-07 12:50 UTC, closed without merging