implemented solution for creating fruit-shop report, based on .csv file
mate-academy/jv-fruit-shop pull request #321
Opened 2022-02-18 15:47 UTC by OlehMytiai

2022-02-18 16:30 UTC, DaniilOpryshko approved these changes
LGTM!

2022-02-21 11:59 UTC, KostyaNikiforov requested changes

2022-02-21 11:59 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/dao/FruitDaoImpl.java
> +        Storage.fruits.put(fruit, Storage.fruits.get(fruit) - amount);
What if the amount turns out to be more than what we already have in storage?

2022-02-21 11:59 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/service/impl/FileReaderServiceImpl.java
> +                    .skip(1)
Why do we skip one line here? If it a specific for SCV file we should name our class not just a FileReaderService. And also better make it constant

2022-02-21 11:59 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/dao/FruitDaoImpl.java
> +        Storage.fruits.put(fruit, Storage.fruits.get(fruit) - amount);
Методы слоя Dao предназначены для выполнения простых операций с объектами хранящимися в базе данных. В твоём случае ты не просто читаешь или обновляешь данные, ты выполняешь бизнес логику по обновлению значения, в то время как метод update должен выполнять только одну функцию - засечивать полученные данные в необходимое поле. Поэтому лучше упростить этот класс или переименовать в Service.

2022-02-21 13:54 UTC, KostyaNikiforov approved these changes

2022-02-21 13:54 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/dao/FruitDaoImpl.java
> +
Empty line

2022-11-12 22:52 UTC, closed without merging