Jv homework fruit shop v.2
mate-academy/jv-fruit-shop pull request #353
Opened 2022-04-27 13:52 UTC by etezaadi

2022-04-27 15:33 UTC, Nick97-git requested changes

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/CsvFileReaderService.java
> +    List<String> fileReader(String fileName);
```suggestion
    List<String> readFromFile(String fileName);
```

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/CsvFileWriterService.java
> +    void fileWriter(String fileName);
```suggestion
    void writeToFile(String fileName);
```

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/FruitTransaction.java
> +public interface FruitTransaction {
```suggestion
public interface FruitTransactionService {
```

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/CsvFileReaderServiceImpl.java
> +
remove empty line

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/CsvFileWriterServiceImpl.java
> +    public static final String COLUMN = "fruit,quantity";
```suggestion
    private static final String HEADER = "fruit,quantity";
```

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/CsvFileWriterServiceImpl.java
> +    }
it's better to create a separate service that will form a report

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/FruitTransactionImpl.java
> +    private static FruitShopDao fruitShopDao = new FruitShopDaoImpl();
let's initialize this field using constructor

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/FruitTransactionImpl.java
> +    private static final int START_FIND_ELEMENTS = 1;
```suggestion
    private static final int LINE_OF_FIRST_OPERATION = 1;
```

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/FruitTransactionImpl.java
> +    private static final int INDEX_NAME = 1;
```suggestion
    private static final int OPERATION_INDEX = 0;
    private static final int NAME_NAME = 1;
```

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/FruitTransactionImpl.java
> +    private static final int INITIALIZATION_QUANTITY_IN_DB = 0;
it's a redundant constant, remove it

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/FruitTransactionImpl.java
> +        validateDB(data);
let's rewrite your logic, so you can remove this method from this class, you don't need to initialize fruits before processing each operation

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/FruitTransactionImpl.java
> +            String[] splitElement = data.get(i).split(SPLIT_CHARACTER);
```suggestion
            String[] splittedLine = lines.get(i).split(SPLIT_CHARACTER);
```

2022-04-27 15:33 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/strategy/OperationHandler.java
> +    void getOperation(String[] data);
```suggestion
    void handle(String fruitName, int quantity);
```

2022-04-28 18:03 UTC, Nick97-git requested changes

2022-04-28 18:03 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/SeparateServiceImpl.java
> +    public static final String HEADER = "fruit,quantity";
```suggestion
    private static final String HEADER = "fruit,quantity";
```

2022-04-28 18:03 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/SeparateServiceImpl.java
> +        for (Map.Entry<String, Integer> output : Storage.fruitStorage.entrySet()) {
let's create a method getAll in FruitShopDao that returns `Storage.fruitStorage`;

2022-04-28 18:03 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/SeparateServiceImpl.java
> +        List<String> fromMapToList = new ArrayList<>();
you don't this list, remove it

2022-04-28 18:03 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/SeparateServiceImpl.java
> +    public List<String> getReportFromList() {
```suggestion
    public String getReportFromList() {
```

2022-04-28 18:03 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/SeparateService.java
> +    List<String> getReportFromList();
```suggestion
    String createReport();
```

2022-04-28 18:03 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/SeparateService.java
> +public interface SeparateService {
```suggestion
public interface ReportService {
```

2022-04-29 04:34 UTC, Nick97-git requested changes

2022-04-29 04:34 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/ReportServiceImpl.java
> +        StringBuilder builder = new StringBuilder();
```suggestion
        StringBuilder reportBuilder = new StringBuilder();
```

2022-04-29 04:34 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/impl/ReportServiceImpl.java
> +    private FruitShopDao fruitShopDao = new FruitShopDaoImpl();
initialize this field, using constructor

2022-04-29 09:18 UTC, etezaadi commented
@Nick97-git i thank you for your help :)

2022-04-29 10:09 UTC, Nick97-git approved these changes

2024-08-27 08:52 UTC, closed without merging