hw-fruit-shop
mate-academy/jv-fruit-shop pull request #416
Opened 2022-06-21 19:07 UTC by TymurTsvietkov

2022-06-22 13:04 UTC, Vasyl-Bevz requested changes

2022-06-22 13:04 UTC, Vasyl-Bevz commented on src/main/java/service/impl/ProcessDataServiceImpl.java
> +        }
Тут наче дві дії різні виконуються: 1. Це парсінг строк на значення. 2. Підрахунок кількості. Може на два сервіси розбити?

2022-06-22 14:32 UTC, Vasyl-Bevz approved these changes

2022-06-22 15:06 UTC, liliia-ponomarenko requested changes
давай допрацюємо твоє рішення

2022-06-22 15:06 UTC, liliia-ponomarenko commented on src/main/resources/to.csv
> +apple,90
краще щоб файл звіту не закінчувався пустим рядком

2022-06-22 15:06 UTC, liliia-ponomarenko commented on src/main/resources/from.csv
> +type,fruit,quantity
папка resources повинна бути системною main -> new -> directory 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/96740815/175042633-df18abc3-a2d5-4190-b095-70e99e964c44.png">

2022-06-22 15:06 UTC, liliia-ponomarenko commented on src/main/java/strategy/OperationStrategy.java
> +        switch (operation) {
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/96740815/175064115-8bf382a7-c6df-4534-b4ba-11ada84f1956.png">

2022-06-22 15:06 UTC, liliia-ponomarenko commented on src/main/java/db/Storage.java
> +    public static final Map<String, Integer> storage = new HashMap<>();
було б добре додати модель Fruit

2022-06-23 06:36 UTC, liliia-ponomarenko requested changes

2022-06-23 06:36 UTC, liliia-ponomarenko commented on src/main/java/model/Fruit.java
> +    private final OperationHandler operation;
```suggestion
public class FruitTransportation {
    private final Operation operation;
```
хендлер не може бути полем можелі ( це порушення принципів SOLID)  стратегія реалізується на рівні сервісів

2022-06-23 06:36 UTC, liliia-ponomarenko commented on src/main/java/strategy/OperationStrategy.java
> +    private static Map<Operation, OperationHandler> operationHandler = null;
```suggestion
    private static Map<Operation, OperationHandler> operationHandler;
```

2022-06-23 07:06 UTC, liliia-ponomarenko requested changes

2022-06-23 07:06 UTC, liliia-ponomarenko commented on src/main/java/dao/StorageDaoImpl.java
> +        addNewFruit(fruit);
тут те саме що з моделлю "стратегія реалізується на рівні сервісів" 
dao це рівень взаємодії з БД

2022-06-23 07:06 UTC, liliia-ponomarenko commented on src/main/java/service/impl/ReportGeneratingServiceImpl.java
> +            report.add(fruit.getFruitType() + CSV_SEPARATOR + fruit.getQuantity());
```suggestion
            report.add(System.lineSeparator() + fruit.getFruitType() 
            + CSV_SEPARATOR + fruit.getQuantity());
```

2022-06-23 07:06 UTC, liliia-ponomarenko commented on src/main/java/service/impl/ReportWriterServiceImpl.java
> +            bufferedWriter.write(reports.get(reports.size() - 1));
```suggestion
            for (int i = 0; i < reports.size(); i++) { // use for-each 
                bufferedWriter.write(reports.get(i));
            }
```
це хардкод

2022-06-23 07:06 UTC, liliia-ponomarenko commented on src/main/my-resources/activities.csv
> +type,fruit,quantity
папка resources повинна бути системною main -> new -> directory 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/96740815/175042633-df18abc3-a2d5-4190-b095-70e99e964c44.png">

2022-06-23 12:53 UTC, liliia-ponomarenko approved these changes
good job ☺️

2025-10-28 15:20 UTC, closed without merging