FruitShopApp created.
mate-academy/jv-fruit-shop pull request #457
Opened 2022-08-24 13:55 UTC by SpaceUrgent

for creating the report on fruits balances:
TransactionParserImpl by input file name gets records from input file (csv) using FruitDaoImpl and parses each record in order to return a list of FruitTransactions. After that transactions passed to ReportBuilderImpl and ready report is saved as csv file through FruitDaoImpl.

2022-08-24 14:37 UTC, aaananas requested changes

2022-08-24 14:37 UTC, aaananas commented on src/main/java/core/basesyntax/FruitShopApp.java
> +        List<FruitTransaction> fruitTransactions = app.parser.getTransactions("transactions.csv");
![image](https://user-images.githubusercontent.com/81781479/186446076-509438e3-440a-414d-9d62-a5696ad65b2b.png)
you should create FileReader, FileWriter, TransactionParser, FruitShopService, ReportCreator and implementations, OperationHandler and handler for each operation
Implement pattern strategy

2022-08-24 16:48 UTC, aaananas requested changes

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/ReportBuilderImpl.java
> +    }
create an interface OperationHandler, and 2 implementations SubstractOperationHandler and AddOperationHandler

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/ReportBuilderImpl.java
> +public class ReportBuilderImpl implements ReportBuilder {
```suggestion
public class CsvReportCreatorImpl implements ReportCreator {
```

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/RecordsReader.java
> +public interface RecordsReader {
```suggestion
public interface FileReader {
```

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/ReportBuilder.java
> +public interface ReportBuilder {
```suggestion
public interface ReportCreator {
```

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/ReportBuilder.java
> +    List<String> getReport(List<FruitTransaction> transactions);
```suggestion
    String getReport(Map<String, Integer> data);
```
create storage to store fruit information, get that data and pass here in this method as a parameter

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/ReportWriter.java
> +public interface ReportWriter {
```suggestion
public interface FileWriter {
```

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/ReportWriter.java
> +    void writeReport(String targetFileName, List<String> report);
```suggestion
    void writeReport(String targetFileName, String data);
```

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/RecordsReaderImpl.java
> +public class RecordsReaderImpl implements RecordsReader {
```suggestion
public class FileReaderImpl implements FileReader {
```

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/ReportWriterImpl.java
> +public class ReportWriterImpl implements ReportWriter {
```suggestion
public class FileWriterImpl implements FileWriter {
```

2022-08-24 16:48 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/ReportWriterImpl.java
> +    public void writeReport(String targetFileName, List<String> report) {
```suggestion
    public void writeToFile(String targetFileName, String data) {
```

2022-08-24 19:09 UTC, aaananas requested changes

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/FruitShopService.java
> +        return balances;
```suggestion
    public Map<String, Integer> getBalance() {
        return storageDao.getAl();
```

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/FruitShopService.java
> +    }
```suggestion
```

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/service/impl/ReportCreatorImpl.java
> +public class ReportCreatorImpl implements ReportCreator {
```suggestion
public class CsvReportCreatorImpl implements ReportCreator {
```

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/strategy/impl/OperationStrategyImpl.java
> +}
```suggestion
public class OperationStrategyImpl implements OperationStrategy {
    private final Map<Operation, OperationHandler> handlersMap;
    
    public OperationStrategyImpl(Map<Operation, OPerationHandler> handlersMap) {
        this.handlersMap = handlersMap;
    }
    
    @Override
    public OperationHandler get(Operation operation) {
         return handlerMap.get(operation);
    }
}
```

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/strategy/OperationStrategy.java
> +    OperationHandler getOperationHandler(TurnoverType type);
```suggestion
    OperationHandler get(Operation operation);
```

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/hadler/OperationHandler.java
> +    int getAmount(String fruit, List<FruitTransaction> transactions);
```suggestion
    void handle(FruitTransaction transaction);
```

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/hadler/impl/SubtractOperationHandler.java
> +    public int getAmount(String fruit, List<FruitTransaction> transactions) {
```suggestion
    public void handle(FruitTransaction transaction) {
```

2022-08-24 19:09 UTC, aaananas commented on src/main/java/core/basesyntax/hadler/impl/AddOperationHandler.java
> +    public int getAmount(String fruit, List<FruitTransaction> transactions) {
```suggestion
public class AddOperationHandler implements OperationHandler {
    private final StorageDao storageDao;
    
    public AddOperationHandler(StorageDao storageDao) {
        this.storageDao = storageDao;
    }
    
    @Override
    public void handle(FruitTransaction transaction) {
```

2022-08-25 18:49 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/service/impl/CsvFileWriter.java
> +public class CsvFileWriter implements FileWriter {
keep name consistent. if we have FileReader, not a CsvFileReader, why we should have CsvFileWriter?
use FileWriterImpl

2022-08-25 19:01 UTC, kozhukhovsky requested changes
Not all comments are fixed. 
Also added some new comments :)

2022-08-25 19:01 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/hadler/impl/ReturnOperationHandler.java
> +        storageDao.save(transaction.getFruit(),
returnOperationHandler сontains the same logic, as supplyOperationHandler

2022-08-26 07:49 UTC, MaliukDaria requested changes

2022-08-26 07:49 UTC, MaliukDaria commented on src/main/java/core/basesyntax/service/impl/CsvFileWriterImpl.java
> +            BufferedWriter reportWriter = new BufferedWriter(new java.io.FileWriter(reportFile));
Lets use try with resources here

2022-08-26 07:49 UTC, MaliukDaria commented on src/main/java/core/basesyntax/hadler/impl/BalanceOperationHandler.java
> +        transaction.getOperation().equals(Operation.BALANCE);
why do we need this?

2022-08-26 07:49 UTC, MaliukDaria commented on src/main/java/core/basesyntax/enums/Operation.java
> +public enum Operation {
I think we can make this enum as inner to Fruit Transaction class

2022-08-26 12:07 UTC, MaliukDaria approved these changes

2025-03-09 18:12 UTC, closed without merging