Created structure for different logics. Created implementation for the logics.
mate-academy/jv-fruit-shop pull request #588
Opened 2022-12-08 19:42 UTC by BusyhinD

Implemented strategy pattern for the shop operations.

2022-12-09 11:59 UTC, Rommelua requested changes
Просьба привести программу в соответствие с заданием и прислать на повторную проверку.

2022-12-09 11:59 UTC, Rommelua commented on src/main/java/Main.java
> +                        .createNewTransaction("p", "apple", 20));
По первому пункту условия нужно считать данные из файла. Тут вручную создаются транзакции в main методе.
![image](https://user-images.githubusercontent.com/20326858/206697619-e1a2713e-132e-4088-89a1-2f3e7e9bb22b.png)

2022-12-12 14:59 UTC, aaananas requested changes

2022-12-12 14:59 UTC, aaananas commented on src/main/java/Main.java
> +        ReaderService readerService = new ReaderServiceImpl(fruitTransactionService);
```suggestion
        ReaderService readerService = new ReaderServiceImpl();
```
reader повинен просто читати дані з файла

2022-12-12 14:59 UTC, aaananas commented on src/main/java/db/Storage.java
> +    public static final List<FruitTransaction> transactions = new ArrayList<>();
```suggestion
    public static final Map<String, Integer> fruitStorage = new ArrayList<>();
```
тобі потрібно зберігати фрукти і їх кількість

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/ActivityStrategy.java
> +    FruitTransaction.Operation getOperation(String operation);
цей метод повинен бути в єнамі

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/ActivityStrategyImpl.java
> +    }
```suggestion
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/FruitTransactionService.java
> +    FruitTransaction createNewTransaction(String transaction);
```suggestion
public interface FruitTransactionPareser {
    List<FruitTransaction> parse(List<String> lines);
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/ReaderService.java
> +    List<FruitTransaction> read(Path path);
```suggestion
    List<String> read(String path);
```
Reader читає текст

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/ReportService.java
> +    String createReport(List<FruitTransaction> fruitTransactions);
```suggestion
    String createReport(Map<String, Integer> fruits);
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/activity/ActivityHandler.java
> +                                      FruitTransaction fruitTransaction);
```suggestion
    void doActivity(FruitTransaction fruitTransaction);
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/dao/FruitTransactionDaoImpl.java
> +public class FruitTransactionDaoImpl implements FruitTransactionDao {
для транзакцій не потрібно дао

2022-12-12 14:59 UTC, aaananas commented on src/main/java/Main.java
> +                FruitTransaction.Operation.BALANCE, new BalanceActivityHandler());
```suggestion
        operationActivityHandlerMap.put(
                FruitTransaction.Operation.BALANCE, new BalanceActivityHandler(fruitStorageDao));
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/ShopServiceImpl.java
> +    private static final Path REPORT_PATH = Paths.get("src/main/resources/report.Csv");
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/81781479/207075267-36e7c43e-f6d9-4728-94e1-c64f7f7ed387.png">

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/ShopServiceImpl.java
> +        return fruitTransactionDao.addAll(readerService.read(DATA_PATH));
```suggestion
    public void processTransactions(List<FruitTransaction> transactions) {
        for (FruitTransaction transaction: transactions) {
            strategy.getHandler(transaction.getOperation()).handle(transaction);
        }
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/ShopServiceImpl.java
> +                .createReport(fruitTransactionDao.getAll()), REPORT_PATH);
```suggestion
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/service/WriterService.java
> +    boolean write(String transactions, Path path);
```suggestion
    void write(String data, String toFile);
```

2022-12-12 14:59 UTC, aaananas commented on src/main/java/Main.java
> +        shopService.createReport();
```suggestion
        List<String> dataFromFile = fileReader.read(FROM_FILE);
        List<FruitTransaction> transactions =  reportParser.parse(dataFromFile);
        shopService.processTransactions(transactions);
        String report = reportService.createReport(fruitStorageDao.getAll());
        fileWriter(report, TO_FILE);
```

2022-12-17 12:42 UTC, zachar-chorny requested changes

2022-12-17 12:42 UTC, zachar-chorny commented on src/main/java/service/activity/PurchaseActivityHandler.java
> +        }
You call the getAmountByFruit(fruit) method 3 times, what about writing it into a variable? Also combine these two checks into one

2022-12-17 12:42 UTC, zachar-chorny commented on src/main/java/service/activity/ReturnActivityHandler.java
> +                fruitStorageDao.getAmountByFruit(fruit) + returnAmount);
Why put something that is already there? Why not just do nothing if getAmountByFruit(fruit) == null?

2022-12-17 12:42 UTC, zachar-chorny commented on src/main/java/service/activity/SupplyActivityHandler.java
> +            return fruitStorageDao.add(fruit, supplyAmount);
same

2022-12-17 17:38 UTC, zachar-chorny approved these changes

2022-12-17 17:38 UTC, zachar-chorny commented on src/main/java/service/activity/PurchaseActivityHandler.java
> +        if (fruitStorageDao.getAmountByFruit(fruit) == null
```suggestion
        Integer currentAmount = fruitStorageDao.getAmountByFruit(fruit);
        if (currentAmount == null
```

2022-12-17 18:18 UTC, BusyhinD commented on src/main/java/service/activity/PurchaseActivityHandler.java
> +        if (fruitStorageDao.getAmountByFruit(fruit) == null
Thank you!

2024-02-13 21:00 UTC, closed without merging