1st try commit 13/01
mate-academy/jv-fruit-shop pull request #620
Opened 2023-01-12 23:09 UTC by Watxesnavo

2023-01-13 18:26 UTC, nacenik requested changes

2023-01-13 18:26 UTC, nacenik commented on src/main/java/core/basesyntax/service/file/work/CsvFileWriterServiceImpl.java
> +    private String convertToCsv(FruitTransaction transaction) {
This logic should be in FruitTransactionReportMakerImpl. CsvFileWriterServiceImpl should only write to file.

2023-01-13 18:26 UTC, nacenik commented on src/main/java/core/basesyntax/service/operations/FruitTransactionCreationServiceImpl.java
> +            if (parameters[0].equals(FruitTransaction.Operation.BALANCE.getOperation())) {
This if statement is useless. You have an enum and you can get value using `FruitTransaction.Operation.fromString()`

2023-01-13 18:26 UTC, nacenik commented on src/main/java/core/basesyntax/service/operations/FruitTransactionCreationServiceImpl.java
> +            fruit = parameters[1];
All magic numbers should be constant

2023-01-13 18:26 UTC, nacenik commented on src/main/java/core/basesyntax/service/operations/FruitTransactionReportMakerImpl.java
> +        for (FruitTransaction currentFruitTransaction : balanceList) {
it's not a strategy pattern. You should create additional service called OperationStrategy,  OperationHendler interface with one method `handle()`, and four realizations of this interface (according to the operation). OperationStrategy should contains map with FruitTransaction.Operation key and with OperationHandler value.

2023-01-18 11:01 UTC, nacenik commented on src/main/java/core/basesyntax/service/operations/FruitTransactionCreationServiceImpl.java
> +            for (FruitTransaction.Operation op : FruitTransaction.Operation.values()) {
You don't need loop here. You can use simple:
`FruitTransaction.Operation operation = FruitTransaction.Operation.get(operationValue)` cause you have a map with all operation.

2023-01-18 11:09 UTC, nacenik commented on src/main/java/core/basesyntax/dao/FruitDao.java
> +    List<FruitTransaction> getByOperation(String operation);
Useless method. BALANCE operation should be a part of strategy.

2023-01-18 11:11 UTC, nacenik commented on src/main/java/core/basesyntax/service/file/work/CsvFileWriterService.java
> +    void writeToFile(String writeToFileName, List<FruitTransaction> data);
```suggestion
    void writeToFile(String writeToFileName, String report);
```

2023-01-18 11:21 UTC, nacenik commented on src/main/java/core/basesyntax/strategy/PurchaseOperationHandler.java
> +                int currentAmount = currentFruitBalanceTransaction.getQuantity();
What happen if you try to buy more, than you have?

2023-01-18 11:23 UTC, nacenik commented on src/main/java/core/basesyntax/service/operations/FruitTransactionCreationServiceImpl.java
> +            String fruitType = parameters[1];
Create constants for indexes 0, 1, 2

2023-01-27 12:34 UTC, okuzan commented on src/main/java/core/basesyntax/Main.java
> +                .readFile("src/main/resources/readFromFile.csv");
string path should be constant

2023-01-27 15:53 UTC, andriy-shulepa requested changes

2023-01-27 15:53 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/service/impl/FruitTransactionOperationsCalculatorImpl.java
> +            if (transaction.getOperation().toString().equalsIgnoreCase("b")) {
replace this ifs by operationStrategy.get(transaction.getOperation())

2023-01-27 15:53 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/strategy/PurchaseOperationHandler.java
> +        List<FruitTransaction> balance = dao.getByOperation("b");
use operation enum instead of plain string here and in other handlers

2023-01-28 10:22 UTC, andriy-shulepa requested changes

2023-01-28 10:22 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/service/impl/FruitTransactionCreationServiceImpl.java
> +            operationValue = parameters[0];
move magic numbers to constants

2023-01-28 10:22 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/service/impl/FruitTransactionCreationServiceImpl.java
> +
needless empty line

2023-01-28 10:22 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/service/impl/FruitTransactionCreationServiceImpl.java
> +    private static String operationValue = "b";
use enum instad of string literal

2023-01-28 10:22 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/service/impl/FruitTransactionCreationServiceImpl.java
> +            for (FruitTransaction.Operation op : FruitTransaction.Operation.values()) {
in can be simplified because you have to compare actual and expected operations. no need to iterate through all operation values

2023-01-28 10:23 UTC, andriy-shulepa commented
don't write code to master branch, create new branch for this

2023-02-01 11:15 UTC, nacenik requested changes

2023-02-01 11:15 UTC, nacenik commented on src/main/java/core/basesyntax/service/impl/FruitTransactionCreationServiceImpl.java
> +    private static int fruitQuantity = 0;
Create this variable in a place where you use it.
```suggestion
```

2023-02-01 11:15 UTC, nacenik commented on src/main/java/core/basesyntax/strategy/PurchaseOperationHandler.java
> +                }
you can add your own message for an exception, but it should be with a good description 
```suggestion
                if (balanceFruitQuantity < quantityToRemove) {
                    throw new RuntimeException("Cannot purchase " + quantityToRemove + transaction.getFruit() +  " fruit, cause shop has only " + balanceFruitQuantity);
                }
                balanceFruit.setQuantity(balanceFruitQuantity - quantityToRemove);
```

2023-02-07 11:37 UTC, okuzan commented on src/main/java/core/basesyntax/Main.java
> +                .readFile(fileToReadPath);
```suggestion
        List<String[]> fileData = fileReaderService.readFile(fileToReadPath);
```

2023-02-07 12:18 UTC, okuzan requested changes
Good job overall!

2023-02-07 12:18 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/FruitTransactionCreationServiceImpl.java
> +    private static final int THIRD_POSITION = 2;
it's not informative naming for the constants, it's clear from the value itself, let's call them FRUIT_TYPE_INDEX, QUANTITY_INDEX, etc

2023-02-07 12:18 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/CsvFileReaderServiceImpl.java
> +                data.add(line.split(","));
delimiter better be constant too

2023-02-07 12:18 UTC, okuzan commented on src/main/java/core/basesyntax/model/FruitTransaction.java
> +
delete empty line

2023-02-08 11:07 UTC, kozhukhovsky approved these changes

2024-10-31 17:42 UTC, closed without merging