implemented fruit shop task
mate-academy/jv-fruit-shop pull request #862
Opened 2023-08-01 16:58 UTC by IvanFadieiev

2023-08-01 18:38 UTC, IhorKalaur approved these changes
looks good for me

2023-08-02 07:30 UTC, nacenik requested changes
good solution, let's improve it a little bit :)

2023-08-02 07:30 UTC, nacenik commented on src/main/java/core/basesyntax/db/Storage.java
> +    }
I'd recommend you make storage public static final and use it directly in your program. This is just a mock for the database (if we talk about a real program). That avoids you to put storage as a parameter in your services

2023-08-02 07:30 UTC, nacenik commented on src/main/java/core/basesyntax/operations/PurchaseOperation.java
> +            throw new RuntimeException("Quantity value can't be less than zero");
uninformative message. If I want to buy 10 bananas and you have only 5 how will I know it? How many attempts do I need to do to find the maximum amount that I could buy?

2023-08-02 07:30 UTC, nacenik commented on src/main/java/core/basesyntax/serviceimpl/StorageFillingImpl.java
> +package core.basesyntax.serviceimpl;
if you do separate packages for interface and implementations - follow this structure 
```suggestion
package core.basesyntax.service.impl;
```

2023-08-02 07:30 UTC, nacenik commented on src/main/java/core/basesyntax/service/StorageFilling.java
> +public interface StorageFilling {
```suggestion
public interface FruitShopService {
```

2023-08-02 07:30 UTC, nacenik commented on src/main/java/core/basesyntax/serviceimpl/HandlerReceiverImpl.java
> +        }
Use map instead of switch 
![image](https://github.com/mate-academy/jv-fruit-shop/assets/32339836/21ee1459-ae66-44f5-8e0f-0438f3d04a7e)

2023-08-02 07:30 UTC, nacenik commented on src/main/java/core/basesyntax/serviceimpl/StorageFillingImpl.java
> +    }
your service modifies data, after this - processes it, and brakes the Single responsibility principle. You need to use an additional model to work. 
![image](https://github.com/mate-academy/jv-fruit-shop/assets/32339836/54a93992-9b9b-4d6f-8c67-a1bfb9a7ad4a)

2023-08-02 15:32 UTC, vovasalyha requested changes
Almost done :) added few comments

2023-08-02 15:32 UTC, vovasalyha commented on src/main/java/core/basesyntax/Main.java
>          final String reportPath = "src/main/resources/report.csv";
File paths can be constants

2023-08-02 15:32 UTC, vovasalyha commented on src/main/java/core/basesyntax/model/FruitTransaction.java
> +    private Operation operation;
Make your fields final if you do not plan to modify them

2023-08-02 15:32 UTC, vovasalyha commented on src/main/java/core/basesyntax/operations/PurchaseOperation.java
>          storage.getStorage().put(fruit, storage.getStorage().get(fruit) - quantity);
You are using `storage.getStorage().get(fruit)` several times here, maybe it worths creating variable for better readability?

2023-08-02 15:32 UTC, vovasalyha commented on src/main/java/core/basesyntax/service/FruitShopService.java
> +    void addToStorage(FruitTransaction fruitTransaction, Storage storage,
It's better to use more generic name (`process` for example) as your service is not only adding.

2023-08-02 15:32 UTC, vovasalyha commented on src/main/java/core/basesyntax/service/impl/DataParsesImpl.java
> +    private static final String COMA = ",";
```suggestion
private static final String COMMA = ",";
```

2023-08-02 15:32 UTC, vovasalyha commented on src/main/java/core/basesyntax/service/impl/DataParsesImpl.java
> +public class DataParsesImpl implements DataParser {
```suggestion
public class DataParserImpl implements DataParser {
```

2023-08-03 13:15 UTC, vovasalyha approved these changes
Nice, approved. But don't forget about constants naming pattern :)

2026-07-11 10:06 UTC, closed without merging