my implementation of fruit-shop using SOLID principles
mate-academy/jv-fruit-shop pull request #944
Opened 2023-10-03 09:38 UTC by happytroya

я не використовував клас Storage, можливо так теж підійде?

2023-10-04 11:41 UTC, okuzan requested changes
Good job overall! In handlers, just call your "DB" (public HashMap) instead of passing and returning it

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/ParserServiceImpl.java
> +        throw new RuntimeException("No operation was found: " + operationCode);
throw IllegalArgumentException. Put this method inside of enum

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/strategy/impl/OperationStrategyImpl.java
> +        operationHandlerMap.put(FruitTransaction.Operation.BALANCE, new BalanceHandler());
better pass the whole map to the constructor as a dependency, this will make this class more flexible

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/ParserServiceImpl.java
> +                .map(s -> s.split(","))
```suggestion
                .map(line -> line.split(SEPARATOR))
```

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/ParserServiceImpl.java
> +                                Integer.parseInt(transaction[2].trim()))
Extract indexes to constants with descriptive names. Also, handle malformed input here - what if we aren't able to parse exception and amount?

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/ReaderServiceImpl.java
> +            throw new RuntimeException("Something is wrong", e);
include filename to facilitate debugging

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/ReportServiceImpl.java
> +                .map(entry -> "%s,%s".formatted(entry.getKey(), entry.getValue()))
extract to REGEX, HEADER constants

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/service/impl/WriterServiceImpl.java
> +            Files.write(Path.of("src/main/resources/report"),report);
pass this as another argument

2023-10-04 11:41 UTC, okuzan commented on src/main/java/core/basesyntax/strategy/impl/PurchaseHandler.java
> +            throw new RuntimeException("out of fruits");
```suggestion
            throw new RuntimeException("Not enough of "+ fruit + " to perform this operation");
```

2023-10-05 14:20 UTC, olekskov approved these changes

2024-05-13 10:14 UTC, closed without merging